name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  old:
    runs-on: ubuntu-latest
    steps:
      - name: Generate timestamp
        id: timestamp
        run: |
          timestamp=$(date +%s)
          echo "Timestamp is ${timestamp}"
          echo "::set-output name=value::$timestamp" >> $GITHUB_OUTPUT
      
      - name: Check timestamp
        run: |
          timestamp=${{ steps.timestamp.output.value }}
          echo "Env var is $timestamp"
  
  new:
    runs-on: ubuntu-latest
    steps:
      - name: Generate timestamp
        id: timestamp
        run: |
          timestamp=$(date +%s)
          echo "Timestamp is ${timestamp}"
          echo "value=${timestamp}" >> $GITHUB_OUTPUT

      - name: Check timestamp
        run: |
          timestamp=${{ steps.timestamp.output.value }}
          echo "Env var is $timestamp"
