name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "src/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "contrib/**"
      - "Dockerfile"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spot-check-make:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: e2e/go.mod
          cache-dependency-path: e2e/go.sum
      - name: Check make
        run: |
          make install.dependencies
          make clean
