name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "src/**"
  pull_request:
    paths:
     - ".github/workflows/ci.yaml"
      - "bin/**"
      - "e2e/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  git-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest awslabs/git-secrets repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: awslabs/git-secrets
          ref: 1.3.0
          fetch-tags: true
          path: git-secrets
      - name: Install git secrets from source
        run: sudo make install
        working-directory: git-secrets
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Scan repository for git secrets
        run: |
          git secrets --register-aws
          git secrets --scan-history

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
        with:
          version: v0.10.0
          scandir: "bin/"
